#! /bin/sh
# Starts and stops flask
# /etc/init.d/flask-service
### BEGIN INIT INFO
# Provides:     flask-service
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    flask initialization
### END INIT INFO
# Install with: sudo update-rc.d ledscape-service defaults
PIDFILE=/var/run/flask.pid
LOGFILE=/var/log/flask.log

case "$1" in
start)
        echo "Starting Flask JellyWebUI..."
        cd /opt/git/kingjelly/misc/flask
        nohup /usr/bin/python /opt/git/kingjelly/misc/flask/JellyWebUI.py > /dev/null &
        echo $! > $PIDFILE
;;
stop)
        echo "Stopping Flask JellyWebUI..."
        kill `cat $PIDFILE`
        rm -f $PIDFILE
;;
restart)
        echo "Restarting Flask JellyWebUI..."
        $0 stop
        $0 start
;;
*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

