#! /bin/sh
# Starts and stops kingjelly
# /etc/init.d/kingjelly-service
### BEGIN INIT INFO
# Provides:     kingjelly-service
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    kingjelly initialization
### END INIT INFO
# Install with: sudo update-rc.d kingjelly-service defaults
PIDFILE=/var/run/kingjelly.pid
LOGFILE=/var/log/kingjelly.log

case "$1" in
start)
        echo "Starting kingjelly..."
        nohup /opt/git/kingjelly/Release/kingjelly -layout /opt/git/kingjelly/scripts/jelly16x100.json > $LOGFILE &
        echo $! > $PIDFILE
;;
stop)
        echo "Stopping kingjelly..."
        kill `cat $PIDFILE`
        rm -f $PIDFILE
;;
restart)
        echo "Restarting kingjelly..."
        $0 stop
        $0 start
;;
*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

