#! /bin/sh
# Starts and stops opc-server
# /etc/init.d/ledscape-service
### BEGIN INIT INFO
# Provides:     ledscape-service
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    ledscape initialization
### END INIT INFO
# Install with: sudo update-rc.d ledscape-service defaults
PIDFILE=/var/run/ledscape.pid
LOGFILE=/var/log/ledscape.log

case "$1" in
start)
        echo "Starting LEDscape..."
        modprobe uio_pruss
        cd /opt/git/LEDscape
	# 100 leds, no interpolation or dithering, disable 2nd PRU
        nohup ./opc-server -c 100 -i -t -1 NOP > $LOGFILE &
        echo $! > $PIDFILE
;;
stop)
        echo "Stopping LEDscape..."
        kill `cat $PIDFILE`
        rm -f $PIDFILE
;;
restart)
        echo "Restarting LEDscape..."
        $0 stop
        $0 start
;;
*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

